[package]
name = "wat"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.0.29", features = ["derive", "suggestions", "color", "wrap_help"] }
exitcode = { version = "1.1.2" }
human-panic = { version = "1.0.3" }
tabled = { version = "0.10.0", features = ["color"] }
tokio = { version = "1.23.0", features = ["full"] }
nom = { version = "7.1.1", features = ["std", "alloc"]}
binary-layout = { version = "3.1.3" }
eyre = { version = "0.6.8" }
color-eyre = { version = "0.6.2" }
memmap2 = { version = "0.5.8" }
inventory = { version = "0.3.2" }

[profile.dev]
opt-level = 0
debug = true
strip = "none"
debug-assertions = true
overflow-checks = true
lto = "off"
incremental = true
panic = "unwind"

[profile.release]
opt-level = 3
debug-assertions = false
overflow-checks = false
lto = "fat"
